In [40]:
#!uv add sqlalchemy psycopg2-binary

Resolved 119 packages in 1.02s
Prepared 3 packages in 537ms
░░░░░░░░░░░░░░░░░░░░ [0/3] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 3 packages in 77ms
 + greenlet==3.3.1
 + psycopg2-binary==2.9.11
 + sqlalchemy==2.0.46

## Imports & Constatns

In [5]:
import pandas as pd
from sqlalchemy import create_engine

In [6]:
base_url = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/"
filename = "yellow_tripdata_2019-01.csv.gz"

## Data Setup

In [7]:
df_p = pd.read_parquet("https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-11.parquet")
df_p.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,7,2025-11-01 00:13:25,2025-11-01 00:13:25,1.0,1.68,1.0,N,43,186,1,14.9,0.00,0.5,1.50,0.00,1.0,22.15,2.5,0.00,0.75
1,2,2025-11-01 00:49:07,2025-11-01 01:01:22,1.0,2.28,1.0,N,142,237,1,14.2,1.00,0.5,4.99,0.00,1.0,24.94,2.5,0.00,0.75
2,1,2025-11-01 00:07:19,2025-11-01 00:20:41,0.0,2.70,1.0,N,163,238,1,15.6,4.25,0.5,4.27,0.00,1.0,25.62,2.5,0.00,0.75
3,2,2025-11-01 00:00:00,2025-11-01 01:01:03,3.0,12.87,1.0,N,138,261,1,66.7,6.00,0.5,0.00,6.94,1.0,86.14,2.5,1.75,0.75
4,1,2025-11-01 00:18:50,2025-11-01 00:49:32,0.0,8.40,1.0,N,138,37,2,39.4,7.75,0.5,0.00,0.00,1.0,48.65,0.0,1.75,0.00

In [8]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4181444 entries, 0 to 4181443
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), object(1)
memory usage: 590.2+ MB

In [9]:
df = pd.read_csv(f"{base_url+filename}", nrows=100)

In [10]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-01-01 00:46:40,2019-01-01 00:53:20,1,1.5,1,N,151,239,1,7.0,0.5,0.5,1.65,0.0,0.3,9.95,NaN
1,1,2019-01-01 00:59:47,2019-01-01 01:18:59,1,2.6,1,N,239,246,1,14.0,0.5,0.5,1.00,0.0,0.3,16.30,NaN
2,2,2018-12-21 13:48:30,2018-12-21 13:52:40,3,0.0,1,N,236,236,1,4.5,0.5,0.5,0.00,0.0,0.3,5.80,NaN
3,2,2018-11-28 15:52:25,2018-11-28 15:55:45,5,0.0,1,N,193,193,2,3.5,0.5,0.5,0.00,0.0,0.3,7.55,NaN
4,2,2018-11-28 15:56:57,2018-11-28 15:58:33,5,0.0,2,N,193,193,2,52.0,0.0,0.5,0.00,0.0,0.3,55.55,NaN

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               100 non-null    int64
 1   tpep_pickup_datetime   100 non-null    object
 2   tpep_dropoff_datetime  100 non-null    object
 3   passenger_count        100 non-null    int64
 4   trip_distance          100 non-null    float64
 5   RatecodeID             100 non-null    int64
 6   store_and_fwd_flag     100 non-null    object
 7   PULocationID           100 non-null    int64
 8   DOLocationID           100 non-null    int64
 9   payment_type           100 non-null    int64
 10  fare_amount            100 non-null    float64
 11  extra                  100 non-null    float64
 12  mta_tax                100 non-null    float64
 13  tip_amount             100 non-null    float64
 14  tolls_amount           100 non-null    float64
 15  improvement_surcharge  100 non-null    float64
 16  total_amount           100 non-null    float64
 17  congestion_surcharge   0 non-null      float64
dtypes: float64(9), int64(6), object(3)
memory usage: 14.2+ KB

In [19]:
dict(df.dtypes)

{'VendorID': dtype('int64'),
 'tpep_pickup_datetime': dtype('O'),
 'tpep_dropoff_datetime': dtype('O'),
 'passenger_count': dtype('int64'),
 'trip_distance': dtype('float64'),
 'RatecodeID': dtype('int64'),
 'store_and_fwd_flag': dtype('O'),
 'PULocationID': dtype('int64'),
 'DOLocationID': dtype('int64'),
 'payment_type': dtype('int64'),
 'fare_amount': dtype('float64'),
 'extra': dtype('float64'),
 'mta_tax': dtype('float64'),
 'tip_amount': dtype('float64'),
 'tolls_amount': dtype('float64'),
 'improvement_surcharge': dtype('float64'),
 'total_amount': dtype('float64'),
 'congestion_surcharge': dtype('float64')}

## Code - Preprocessing and loading

In [11]:
dtypes = {'VendorID': 'int64',
 'passenger_count': 'int64',
 'trip_distance': 'float64',
 'RatecodeID': 'int64',
 'store_and_fwd_flag': 'string',
 'PULocationID': 'int64',
 'DOLocationID': 'int64',
 'payment_type': 'int64',
 'fare_amount': 'float64',
 'extra': 'float64',
 'mta_tax': 'float64',
 'tip_amount': 'float64',
 'tolls_amount': 'float64',
 'improvement_surcharge': 'float64',
 'total_amount': 'float64',
 'congestion_surcharge': 'float64'}

parse_dates = [
    'tpep_pickup_datetime',
    'tpep_dropoff_datetime'
]

In [37]:
df = pd.read_csv(f"{base_url+filename}", nrows=100, dtype=dtypes, parse_dates=parse_dates)
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-01-01 00:46:40,2019-01-01 00:53:20,1,1.5,1,N,151,239,1,7.0,0.5,0.5,1.65,0.0,0.3,9.95,NaN
1,1,2019-01-01 00:59:47,2019-01-01 01:18:59,1,2.6,1,N,239,246,1,14.0,0.5,0.5,1.00,0.0,0.3,16.30,NaN
2,2,2018-12-21 13:48:30,2018-12-21 13:52:40,3,0.0,1,N,236,236,1,4.5,0.5,0.5,0.00,0.0,0.3,5.80,NaN
3,2,2018-11-28 15:52:25,2018-11-28 15:55:45,5,0.0,1,N,193,193,2,3.5,0.5,0.5,0.00,0.0,0.3,7.55,NaN
4,2,2018-11-28 15:56:57,2018-11-28 15:58:33,5,0.0,2,N,193,193,2,52.0,0.0,0.5,0.00,0.0,0.3,55.55,NaN

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               100 non-null    int64
 1   tpep_pickup_datetime   100 non-null    datetime64[ns]
 2   tpep_dropoff_datetime  100 non-null    datetime64[ns]
 3   passenger_count        100 non-null    int64
 4   trip_distance          100 non-null    float64
 5   RatecodeID             100 non-null    int64
 6   store_and_fwd_flag     100 non-null    string
 7   PULocationID           100 non-null    int64
 8   DOLocationID           100 non-null    int64
 9   payment_type           100 non-null    int64
 10  fare_amount            100 non-null    float64
 11  extra                  100 non-null    float64
 12  mta_tax                100 non-null    float64
 13  tip_amount             100 non-null    float64
 14  tolls_amount           100 non-null    float64
 15  improvement_surcharge  100 non-null    float64
 16  total_amount           100 non-null    float64
 17  congestion_surcharge   0 non-null      float64
dtypes: datetime64[ns](2), float64(9), int64(6), string(1)
memory usage: 14.2 KB

## Code - Connecting to DB and uploading the data

In [43]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [46]:
print(pd.io.sql.get_schema(df, name="yellow_taxi_data", con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [50]:
df.head(0).to_sql(name="yellow_taxi_data", con=engine, if_exists='replace')

0

In [12]:
df_iter = pd.read_csv(
    base_url+filename,
    dtype=dtypes,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

In [13]:
import pandas as pd
from sqlalchemy import create_engine
# import click

base_url = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/"
filename = "yellow_tripdata_2019-01.csv.gz"

dtypes = {'VendorID': 'int64',
 'passenger_count': 'int64',
 'trip_distance': 'float64',
 'RatecodeID': 'int64',
 'store_and_fwd_flag': 'string',
 'PULocationID': 'int64',
 'DOLocationID': 'int64',
 'payment_type': 'int64',
 'fare_amount': 'float64',
 'extra': 'float64',
 'mta_tax': 'float64',
 'tip_amount': 'float64',
 'tolls_amount': 'float64',
 'improvement_surcharge': 'float64',
 'total_amount': 'float64',
 'congestion_surcharge': 'float64'}

parse_dates = [
    'tpep_pickup_datetime',
    'tpep_dropoff_datetime'
]


# @click.command()
# @click.option('--pg-user', default='root', help='Postgres User')
# @click.option('--pg-pass', default='root', help='PostgreSQL password')
# @click.option('--pg-host', default='localhost', help='PostgreSQL host')
# @click.option('--pg-port', default=5432, type=int, help='PostgreSQL port')
# @click.option('--pg-db', default='ny_taxi', help='PostgreSQL database name')
# @click.option('--target-table', default='yellow_taxi_data', help='Target table name')

def run(pg_user,pg_pass, pg_host, pg_port, pg_db, target_table):
    print("Hello from data-engg-zoomcamp!")
    engine = create_engine(f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}')
    df_iter = pd.read_csv(base_url+filename, dtype=dtypes, parse_dates=parse_dates, iterator=True, chunksize=10000)

    first = True

    for df_chunk in df_iter:

        if first:
            # Create table schema (no data)
            df_chunk.head(0).to_sql(
                name=target_table,
                con=engine,
                if_exists="replace"
            )
            first = False
            print("Table created")

        # Insert chunk
        df_chunk.to_sql(
            name=target_table,
            con=engine,
            if_exists="append"
        )

        print("Inserted:", len(df_chunk))

In [14]:
pg_user,pg_pass, pg_host, pg_port, pg_db, target_table = "root", "root", "localhost", "5432", "ny_taxi", "yellow_taxi_data"
run(pg_user,pg_pass, pg_host, pg_port, pg_db, target_table)

Hello from data-engg-zoomcamp!
Table created
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000

/tmp/ipykernel_14468/977474455.py:46: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  for df_chunk in df_iter:

Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000

PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)